export default function decorate(b){
  b.classList.add('footer-brand-section');
  const wrapper = b.querySelector('.footer-brand-wrapper');
  if(wrapper) wrapper.classList.add('w-100','footer-brand-bg-boing-neutral-gray-600');
  const primary = b.querySelector('.footer-brand-primary');
  if(primary) primary.classList.add('footer-brand-primary');
  const container = b.querySelectorAll('.footer-brand-container');
  container.forEach(c => c.classList.add('footer-brand-container'));
  const primaryContent = b.querySelector('.footer-brand-primary-content');
  if(primaryContent) primaryContent.classList.add('d-flex','flex-column','flex-md-row','justify-content-md-between','align-items-center');
  const left = b.querySelectorAll('.footer-brand-left');
  left.forEach(l => l.classList.add('d-flex','gap-16','px-10','align-items-center','justify-content-center'));
  const logo = b.querySelector('.footer-brand-logo');
  if(logo) logo.classList.add('d-inline-block','analytics_cta_click');
  const logoImg = b.querySelector('.footer-brand-object-fit-contain');
  if(logoImg) logoImg.classList.add('w-100','h-100');
  const secLogo = b.querySelector('.footer-brand-secondary-logo');
  if(secLogo) secLogo.classList.add('d-inline-block');
  const secLogoImg = secLogo ? secLogo.querySelector('img') : null;
  if(secLogoImg) secLogoImg.classList.add('footer-brand-object-fit-contain','w-100');
  const nav = b.querySelector('.footer-brand-navbar');
  if(nav) nav.classList.add('d-grid','d-md-flex');
  const navLeft = b.querySelector('.footer-brand-navbar-left');
  if(navLeft) navLeft.classList.add('d-flex','flex-column','flex-md-row');
  const navRight = b.querySelector('.footer-brand-navbar-right');
  if(navRight) navRight.classList.add('d-flex','flex-column','flex-md-row');
  const listContainers = b.querySelectorAll('.footer-list-container');
  listContainers.forEach(lc => lc.classList.add('footer-list-container'));
  const lists = b.querySelectorAll('.footer-list');
  lists.forEach(list => list.classList.add('d-flex','align-items-center','justify-content-center','align-items-md-start','flex-column'));
  const listItems = b.querySelectorAll('.footer-list-item');
  listItems.forEach(item => item.classList.add('footer-list-item'));
  const links = b.querySelectorAll('.footer-list-item-link');
  links.forEach(link => link.classList.add('d-inline-block','footer-list-cta-analytics','analytics_cta_click','footer-list-item-link'));
  const secondary = b.querySelector('.footer-brand-secondary');
  if(secondary) secondary.classList.add('footer-brand-secondary');
  const secondaryContent = b.querySelector('.footer-brand-secondary-content');
  if(secondaryContent) secondaryContent.classList.add('d-flex','flex-column','justify-content-md-between','align-items-center');
  const smTitle = b.querySelector('.footer-brand-social-media-title');
  if(smTitle) smTitle.classList.add('footer-brand-social-media-title');
  const smList = b.querySelector('.footer-brand-right-list');
  if(smList) smList.classList.add('d-flex','align-items-center','justify-content-center','px-10','flex-wrap');
  const smItems = b.querySelectorAll('.footer-brand-right-item');
  smItems.forEach(item => item.classList.add('d-flex','justify-content-center','align-items-center'));
  const smLinks = b.querySelectorAll('.footer-brand-right-link');
  smLinks.forEach(link => link.classList.add('d-flex','justify-content-center','align-items-center','analytics_cta_click'));
  const leftList = b.querySelector('.footer-brand-left-list');
  if(leftList) leftList.classList.add('d-flex','align-items-center','justify-content-center','flex-wrap');
  const leftItems = b.querySelectorAll('.footer-brand-left-item');
  leftItems.forEach(item => item.classList.add('footer-brand-left-item','footer-brand-foot-link'));
  const leftLink = b.querySelector('.footer-brand-left-link');
  if(leftLink) leftLink.classList.add('footer-brand-left-link','analytics_cta_click');
  const copyright = b.querySelector('.footer-brand-left-copyright');
  if(copyright) copyright.classList.add('text-center');
  const copyrightText = b.querySelector('.footer-brand-left-text');
  if(copyrightText) copyrightText.classList.add('text-white');
}